[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fuzz]
runs = 1000
seed = '0x2'
# By setting the seed, for this seed every time same random number will be applied in order.
# If seed is not set, random numbers will not be in order and code will break for different resons. 

[invariant]
runs = 128
depth = 15
# Depth will be number of functions called in a single command
# If a contract has 20 function, since we are setting the depth to 15
# In one fuzz run max of 15 functions will be called
fail_on_revert = false

remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
